services:
  - type: web
    name: gpt-webhook
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
